[package]
name = "async-signatory"
version = "1.1.2"
description = "Rust Signatory Kit"
authors = ["cleveng <cleveng@gmail.com>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/cakioe/signatory.git"
rust-version = "1.85.0"
keywords = ["signature", "base64", "md5", "timestamp", "serde"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
md5 = "0.7.0"
chrono = "0.4.40"

[features]
default = []

[package.metadata.docs.rs]
all-features = true
